spring:
  application:
    name: boot-admin

  cloud:
    discovery:
      client:
        simple:
          instances:
            MOTOR-VEHICLE-SERVICE[0]:
              uri:  http://localhost:8081
            LAB-SERVICE[0]:
              uri:  http://localhost:8082

server.port: 8091

management:
  security:
    enabled: false

security:
  user:
    name: admin
    password: adminadmin